# Generated by Django 5.0.3 on 2024-03-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium", "0003_astronomyshow_image"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                fields=("show_session", "row", "seat"),
                name="unique_show_session_row_seat",
            ),
        ),
    ]
